### ISSUE TITLE
Hidden Gems

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/scpr-style-guide#36]
AC

- [x] The hidden gems design is implemented

**Comment by sdillingham** [comment]
Implemented in  https://github.com/SCPR/SCPRv4/pull/562

**Comment by sdillingham** [comment]
Note: Elected to implement this component directly in SCPRv4 because the feature may go away if it doesn't drive retention, and because it's unclear whether this component represents a reusable pattern that should be abstracted.
