### ISSUE TITLE
Homepage Beta: UI improvements

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/scpr-style-guide#45]
AC
- [x] Check it out improvements: list items should switch to vertical rather than horizontal layout on mobile
- [x] Bullet styling is darker
- [x] Remove stroke around slideshow icon

**Comment by sdillingham** [comment]
Addressed in https://github.com/SCPR/scpr-style-guide/pull/46. @Ravenstine you'll need to update SCPRv4 to use v0.2.6 of the style guide (and grab an updated version of the scpr-sprite.svg file) in order to see these changes on the beta homepage.
