### ISSUE TITLE
Media objects: prevent widows, dynamically resize headlines

### ISSUE THREAD

**Issue by sdillingham** [SCPR/scpr-style-guide#8]
AC:

- [x] Implement functions to evaluate headlines to ~~prevent widows and~~ optimize number of lines per headline

**Comment by sdillingham** [comment]
After some research, the clear winner in terms of how to prevent typographic widows is to replace the space between the last two words of a string with an `&nbsp;` character. It's possible to accomplish this with javascript, but that seems like a non-performant solution since we'd want to implement it across all our headlines and teasers.

@Ravenstine, what are your thoughts about adding the non-breaking space to strings by writing a simple Ruby helper instead of Javascript? There are examples out there of Ruby solutions for static site generators like Jekyll and Middleman:

https://github.com/bryanveloso/jekyll-widont

Would it be more performant to do this on the backend than on the front-end?

**Comment by sdillingham** [comment]
For reference, here's how you might accomplish this with Javascript:

https://css-tricks.com/snippets/jquery/add-non-breaking-space-on-title-to-prevent-widows/

We currently use https://github.com/Ravenstine/widowtamer on our site, which is a fork of a repo that hasn't been updated since 2012. It works, but I'm not sure it's the best solution.

**Comment by Ravenstine** [comment]
@sdillingham It seems to me like this is something that could be done in Ruby, unless there’s some reason we’d need the non-breaking spaces to shift around in a headline.  It looks like they would always have the same placement, so the non-breaking space could be generated on indexing so any miniscule computing power would only happen once on the server and not at all on the client.

**Comment by sdillingham** [comment]
I like the idea of it being computed and added to the index. Let's plan to implement this piece in SCPRv4 then.
